version: '3.8'

services:
  frontend:
    build: ./educloud-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3003/api

  backend:
    build: ./educloud-backend
    ports:
      - "3003:3002"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/educloud
      - PORT=3002
    volumes:
      - ./educloud-backend:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: