openapi: 3.0.0
info:
  title: EduCloud Live Class API
  version: 1.0.0
  description: API documentation for EduCloud's live class features

paths:
  /api/courses/{courseId}/live-classes:
    post:
      summary: Create a new live class
      tags: [Live Classes]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: courseId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LiveClassCreate'
      responses:
        201:
          description: Live class created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LiveClassResponse'
        403:
          description: Only course instructor can create live classes
        404:
          description: Course not found

    get:
      summary: Get all live classes for a course
      tags: [Live Classes]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: courseId
          required: true
          schema:
            type: string
        - in: query
          name: status
          schema:
            type: string
            enum: [scheduled, active, ended, cancelled]
      responses:
        200:
          description: List of live classes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LiveClassResponse'

  /api/live-classes/{id}:
    get:
      summary: Get a specific live class
      tags: [Live Classes]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Live class details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LiveClassResponse'
        404:
          description: Live class not found

    patch:
      summary: Update a live class
      tags: [Live Classes]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LiveClassUpdate'
      responses:
        200:
          description: Live class updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LiveClassResponse'
        403:
          description: Only instructor can update live class
        404:
          description: Live class not found

    delete:
      summary: Delete a live class
      tags: [Live Classes]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Live class deleted successfully
        403:
          description: Only instructor can delete live class
        404:
          description: Live class not found

  /api/live-classes/{id}/start:
    post:
      summary: Start a live class
      tags: [Live Classes]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Live class started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LiveClassResponse'
        403:
          description: Only instructor can start live class
        404:
          description: Live class not found

  /api/live-classes/{id}/end:
    post:
      summary: End a live class
      tags: [Live Classes]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Live class ended successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LiveClassResponse'
        403:
          description: Only instructor can end live class
        404:
          description: Live class not found

  /api/live-classes/{id}/join:
    post:
      summary: Join a live class
      tags: [Live Classes]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Joined live class successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LiveClassResponse'
        400:
          description: Live class is not active
        404:
          description: Live class not found

  /api/live-classes/{id}/leave:
    post:
      summary: Leave a live class
      tags: [Live Classes]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Left live class successfully
        404:
          description: Live class not found

components:
  schemas:
    LiveClassCreate:
      type: object
      required:
        - title
        - description
        - scheduledStartTime
        - scheduledEndTime
      properties:
        title:
          type: string
          example: "Introduction to React Hooks"
        description:
          type: string
          example: "Learn about React Hooks and their use cases"
        scheduledStartTime:
          type: string
          format: date-time
          example: "2025-01-03T10:00:00Z"
        scheduledEndTime:
          type: string
          format: date-time
          example: "2025-01-03T11:00:00Z"
        settings:
          type: object
          properties:
            enableChat:
              type: boolean
              default: true
            enableVideo:
              type: boolean
              default: true
            enableAudio:
              type: boolean
              default: true
            allowScreenSharing:
              type: boolean
              default: true
            maxParticipants:
              type: integer
              default: 100

    LiveClassUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        scheduledStartTime:
          type: string
          format: date-time
        scheduledEndTime:
          type: string
          format: date-time
        settings:
          type: object
          properties:
            enableChat:
              type: boolean
            enableVideo:
              type: boolean
            enableAudio:
              type: boolean
            allowScreenSharing:
              type: boolean
            maxParticipants:
              type: integer

    LiveClassResponse:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        course:
          type: string
        instructor:
          $ref: '#/components/schemas/User'
        scheduledStartTime:
          type: string
          format: date-time
        scheduledEndTime:
          type: string
          format: date-time
        actualStartTime:
          type: string
          format: date-time
        actualEndTime:
          type: string
          format: date-time
        status:
          type: string
          enum: [scheduled, active, ended, cancelled]
        participants:
          type: array
          items:
            type: object
            properties:
              user:
                $ref: '#/components/schemas/User'
              joinedAt:
                type: string
                format: date-time
              leftAt:
                type: string
                format: date-time
        settings:
          type: object
          properties:
            enableChat:
              type: boolean
            enableVideo:
              type: boolean
            enableAudio:
              type: boolean
            allowScreenSharing:
              type: boolean
            maxParticipants:
              type: integer
        recording:
          type: object
          properties:
            url:
              type: string
            duration:
              type: number
            size:
              type: number
            createdAt:
              type: string
              format: date-time

    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        avatar:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
